enum SlideType {
  singleText,
  doubleText,
  leftTextRightImage,
  leftTextRightCode,
  leftImageRightText,
  leftImageRightCode,
  leftCodeRightImage,
  singleCode,
  doubleCode,
  plainText,
  textWithCode,
  singleImage,
  unknown,
}
